Vagrant.configure("2") do |config|
  
  config.vm.define "web" do |web|
  web.vm.box = "ubuntu_web"
  web.vm.box_url = "http://files.vagrantup.com/precise32.box"
  web.vm.synced_folder "./app","/var/www/", create:true
  web.vm.network :private_network, ip: "192.168.99.101"
  web.vm.provision "shell", path: "web.sh"
    
config.vm.define "web" do |app|
  web.vm.box = "ubuntu_web"
  web.vm.box_url = "http://files.vagrantup.com/precise32.box"
  web.vm.synced_folder "./app","/var/www/", create:true
  web.vm.network :private_network, ip: "192.168.99.102"
  web.vm.provision "shell", path: "app.sh"
    
config.vm.define "web" do |db|
  web.vm.box = "ubuntu_web"
  web.vm.box_url = "http://files.vagrantup.com/precise32.box"
  web.vm.synced_folder "./app","/var/www/", create:true
  web.vm.network :private_network, ip: "192.168.99.103"
  web.vm.provision "shell", path: "db.sh"
    
config.vm.define "web" do |cache|
  web.vm.box = "ubuntu_web"
  web.vm.box_url = "http://files.vagrantup.com/precise32.box"
  web.vm.synced_folder "./app","/var/www/", create:true
  web.vm.network :private_network, ip: "192.168.99.104"
  web.vm.provision "shell", path: "cache.sh"
    
  
end
