# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
  config.vm.define "web" do |web|
  web.vm.box = "ubuntu_web"
  web.vm.box_url = "http://files.vagrantup.com/precise32.box"
  web.vm.synced_folder "./app","/var/www/", create:true
  web.vm.network :private_network, ip: "192.168.99.101"
  web.vm.provision "shell", path: "web.sh"
    
config.vm.define "web" do |app|
  app.vm.box = "ubuntu_app"
  app.vm.box_url = "http://files.vagrantup.com/precise32.box"
  app.vm.synced_folder "./app","/var/www/", create:true
  app.vm.network :private_network, ip: "192.168.99.102"
  app.vm.provision "shell", path: "app.sh"
    
config.vm.define "web" do |db|
  db.vm.box = "ubuntu_web"
  db.vm.box_url = "http://files.vagrantup.com/precise32.box"
  db.vm.synced_folder "./app","/var/www/", create:true
  db.vm.network :private_network, ip: "192.168.99.103"
  db.vm.provision "shell", path: "db.sh"
    
config.vm.define "web" do |cache|
  cache.vm.box = "ubuntu_web"
  cache.vm.box_url = "http://files.vagrantup.com/precise32.box"
  cache.vm.synced_folder "./app","/var/www/", create:true
  cache.vm.network :private_network, ip: "192.168.99.104"
  cache.vm.provision "shell", path: "cache.sh"
    
  
end
